spring.application.name=cursos
spring.datasource.url=jdbc:h2:mem:cursosdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
# Esta línea es la más importante para evitar el error 500:
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true






